version: '3'

services:
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.php:/var/www/html/index.php
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    volumes:
      - ./index.php:/var/www/html/index.php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: my_user
      PMA_PASSWORD: ()DSUF*()UY$P{()*YHEUW:DFHP(&T@$GRDS:FIOUN

    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: ()DSUF*()UY$P{()*YHEUW:DFHP(&T@$GRDS:FIOUN
      MYSQL_ROOT_PASSWORD: )}DSFH{(*)#$HRN:EFW[90834yrp9[aerwUFGHBAQW;LIRTHY12]]}
    ports:
      - "3306:3306"
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: my_user
      WORDPRESS_DB_PASSWORD: )}DSFH{(*)#$HRN:EFW[90834yrp9[aerwUFGHBAQW;LIRTHY12]]}
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: