version: '3'

services:
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.php:/var/www/html/index.php
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    volumes:
      - ./index.php:/var/www/html/index.php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: my_user
      PMA_PASSWORD: ()DSUF*()UY$P{()*YHEUW:DFHP(&T@$GRDS:FIOUN

    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: ()DSUF*()UY$P{()*YHEUW:DFHP(&T@$GRDS:FIOUN
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
